name: advanced_weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  http: ^1.4.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
